// UI/src/components/LoginComponent.vue
<template>
    <v-container fill-height fluid>
        <v-row align="center" justify="center" dense>
            <v-col 
                :cols="cols"
            >
                <div class="login-form">
                    <v-col align="center"><h2>Login</h2></v-col>
                    <v-col align="center">
                            <h3 :class="{'success': accountCreated, 'error': accountCreatedError}">{{message}}</h3>
                    </v-col>
                    <v-form fluid>
                        <v-text-field
                            class="username"
                            label="Username"
                            hide-details="auto"
                            v-model="username">
                        </v-text-field>
                        <v-text-field
                            class="password"
                            label="Password"
                            type="password"
                            v-model="password">
                        </v-text-field>
                        <v-col align="center">
                            <v-btn
                                medium
                                class="register-button"
                                color="success"
                                justify="center"
                                @click="sendLoginRequest">
                                Login
                            </v-btn>
                        </v-col>
                    </v-form>
                </div>
            </v-col>
        </v-row>
    </v-container>
</template>

<script>
import { AUTH } from '../endpoints/http-config'


  export default {
    name: 'LoginComponent',
    data() {
        return {
            accountCreated: false,
            accountCreatedError: false,
            message: "",
            username: "",
            password: ""
        }
    },
    methods: {
        sendLoginRequest: function () {

            // Build the form data for the login
            const formData = new FormData();
            formData.append('username', this.username);
            formData.append('password', this.password);

            AUTH.post("/login", formData)
                .then(response => {
                    this.message = "Logged In";

                    console.log("Loggin In")
                    console.log(response)
                    this.$store.commit('setToken', response.data.access_token);
                    this.$store.commit('setUser', response.data.username);

                    console.log(`Store Value: ${this.$store.getters.token}`)

                    this.$router.push('habbits');
                })
                .catch((error) => {
                    this.message = "Invalid Credentials."
                    console.log(error);
                })
        }
    },
    computed: {
      cols () {
        switch (this.$vuetify.breakpoint.name) {
            case 'xs': return "10"
            case 'sm': return "6"
            case 'md': return "6"
            case 'lg': return "3"
            case 'xl': return "3"
        }
        return "3"
      },
    }
    }
</script>

<style scoped>

.login-form {
    width: 100%;
    padding: 55px 25px 25px 25px;

    border: 1px solid rgba(0, 0, 0, 0.3);
    box-shadow: rgba(0, 0, 0, 0.55) 0px 5px 15px;

    background-color: rgb(255, 255, 255);
    opacity: 0.9;
}

.error {
    color: red;
}

.success {
    color: green;
}

.register-button {
    margin: 0 auto;
}

.username {
    padding-bottom: 25px;
}

.email {
    padding-bottom: 25px;
}

.password {
    padding-bottom: 25px;
}


.container {
    background-image: url("../assets/login-bg.jpg");
    background-size: cover;
    background-repeat: no-repeat;
}

</style>

// ui/src/views/Login.svelte
<script>
    import { navigate } from "svelte-routing";
    import { AUTH } from '../http'
    import { token } from '../store'

    let email = '';
    let password = '';
    let errorMessage = '';

    function login(){
        let formData = new FormData();
        formData.append('username', email);
        formData.append('password', password);

        AUTH.post('/login', formData)
            .then(response => {
                token.setToken(response.data.access_token);
                navigate('/habits', {replace: true});
            })
            .catch(error => {
                console.log(error);
                errorMessage = error.response.data.detail;
            })
    }

</script>

<main>
    <div class="flex flex-col justify-center min-h-screen min-w-full items-center bg-gray-50">
        <div class="max-w-md w-full space-y-8"></div>
            <div>
                <h1 class="text-3xl font-extrabold text-gray-900 text-center">Log in</h1>
                <p class="mt-2">
                    Or <a class="text-md text-indigo-600 hover:text-indigo-700">register for an account</a>
                </p>
            </div>
            {#if errorMessage != ''}
                <div class="p-2 m-5 border border-red-400 rounded-md text-center">
                    <p>{errorMessage}</p>
                </div>
            {/if}
            <form on:submit|preventDefault={login} class="flex flex-col space-y-6 mt-8">
                <div class="-space-y-px">
                    <input bind:value={email} type="text" placeholder="Email address" class="border border-gray-300 placeholder-gray-500 w-full rounded-t-md"/>
                    <input bind:value={password} type="password" placeholder="Password" class="border border-gray-300 placeholder-gray-500 w-full rounded-b-md"/>
                </div>
                <div class="flex items-center justify-between">
                    <div class="flex items-center">
                        <input id="remember_me" name="remember_me" type="checkbox" class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded">
                        <label for="remember_me" class="ml-2 block text-sm text-gray-900">
                            Remember me
                        </label>
                    </div>
                    <div class="text-sm">
                        <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500">
                          Forgot your password?
                        </a>
                    </div>
                </div>
                <div>
                    <button 
                        class="w-full bg-indigo-600 hover:bg-indigo-700 text-white rounded-md py-2 text-sm font-medium"
                        type="submit"
                    >
                        Log in
                    </button>
                </div>
            </form>
        </div>
</main>
